# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.telesurveillance
canonical: https://interop.esante.gouv.fr/ig/fhir/telesurveillance # the last part of canonical and id must be the same
name: TLSV # Should be an acronym
title: Guide d'implémentation de la télésurveillance
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0-ballot # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    autres_ressources.md:
        title: Autres Ressources
        downloads.md:
            title: Téléchargements et usages

menu:
    Accueil: index.html
    Ressources de conformité: artifacts.html
    Autres ressources:
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
        "Site d'InteropSanté ": new-tab https://www.interopsante.org/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/